# Font
font_family        SauceCodePro Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size        10

# Window
#window_padding_width 14
#hide_window_decorations yes
confirm_os_window_close 0

remember_window_size  no
initial_window_width  1200
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no


# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

map ctrl+shift+left send_text all \x1b[1;6D
map ctrl+shift+right send_text all \x1b[1;6C
map ctrl+shift+up send_text all \x1b[1;6A
map ctrl+shift+down send_text all \x1b[1;6B


# Allow remote access
allow_remote_control yes

# Aesthetics
background_opacity 0.8
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor
enable_audio_bell no
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2


#CUSTOM COLORS

background            #1f1c27
foreground            #b6a0ff
cursor                #b6a0ff
selection_background  #353146
color0                #1f1c27
color8                #353146
color1                #d8393d
color9                #d8393d
color2                #2dcc72
color10               #2dcc72
color3                #d8b76e
color11               #d8b76e
color4                #ffc183
color12               #ffc183
color5                #dd8d40
color13               #dd8d40
color6                #2388ff
color14               #2388ff
color7                #b6a0ff
color15               #e9e4ff
selection_foreground #1f1c27
