hl.on("hyprland.start", function()
	hl.exec_cmd("noctalia")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("eval $(gnome-keyring-daemon --start --components=secrets)")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("awww img /home/mibu/Pictures/Wallpapers/wallpaper.jpg")
	hl.exec_cmd("dunstctl set-paused true")
end)
