unbind = SUPER, Q
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, W, killactive
bind = SUPER , B, exec, $browser
bind = ALT , SPACE, exec, $chat
bind = SUPER, SPACE, exec, $ipc panel-toggle launcher
bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER SHIFT, Print, exec, bash -c 'N=$(ls ~/Pictures/aa/*.png 2>/dev/null | wc -l); grim -g "$(slurp)" ~/Pictures/aa/$((N+1)).png'
# bind = SUPER SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/aa/screenshot_$(date +%Y-%m-%d_%H-%M-%S).png
bind = SUPER, L, exec, hyprlock

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

bind = SUPER, minus, resizeactive, -45 0
bind = SUPER, equal, resizeactive, 45 0
bind = SUPER SHIFT, equal, resizeactive, 0 -45
bind = SUPER SHIFT, minus, resizeactive, 0 45
bind = SUPER, F, fullscreen, 0

